package com.github.bh.aconf.persist.base.mapper;

import com.github.bh.aconf.persist.base.model.AppRegisterMeta;
import com.github.bh.aconf.persist.base.model.AppRegisterMetaExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AppRegisterMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    int countByExample(AppRegisterMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    int deleteByExample(AppRegisterMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    int insert(AppRegisterMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    int insertSelective(AppRegisterMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    List<AppRegisterMeta> selectByExample(AppRegisterMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    AppRegisterMeta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppRegisterMeta record, @Param("example") AppRegisterMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppRegisterMeta record, @Param("example") AppRegisterMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppRegisterMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_register
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppRegisterMeta record);
}