package com.github.bh.aconf.persist.base.mapper;

import com.github.bh.aconf.persist.base.model.BssMeta;
import com.github.bh.aconf.persist.base.model.BssMetaExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BssMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    int countByExample(BssMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    int deleteByExample(BssMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    int insert(BssMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    int insertSelective(BssMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    List<BssMeta> selectByExample(BssMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    BssMeta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BssMeta record, @Param("example") BssMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BssMeta record, @Param("example") BssMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BssMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BssMeta record);
}