package com.github.bh.aconf.persist.base.mapper;

import com.github.bh.aconf.persist.base.model.ConditionMeta;
import com.github.bh.aconf.persist.base.model.ConditionMetaExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ConditionMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    int countByExample(ConditionMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    int deleteByExample(ConditionMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    int insert(ConditionMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    int insertSelective(ConditionMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    List<ConditionMeta> selectByExample(ConditionMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    ConditionMeta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ConditionMeta record, @Param("example") ConditionMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ConditionMeta record, @Param("example") ConditionMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConditionMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConditionMeta record);
}