package com.github.bh.aconf.persist.base.mapper;

import com.github.bh.aconf.persist.base.model.ConfigMeta;
import com.github.bh.aconf.persist.base.model.ConfigMetaExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ConfigMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    int countByExample(ConfigMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    int deleteByExample(ConfigMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    int insert(ConfigMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    int insertSelective(ConfigMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    List<ConfigMeta> selectByExample(ConfigMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    ConfigMeta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ConfigMeta record, @Param("example") ConfigMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ConfigMeta record, @Param("example") ConfigMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfigMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfigMeta record);
}