package com.github.bh.aconf.persist.base.mapper;

import com.github.bh.aconf.persist.base.model.ConfigHistoryMeta;
import com.github.bh.aconf.persist.base.model.ConfigHistoryMetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigHistoryMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    int countByExample(ConfigHistoryMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    int deleteByExample(ConfigHistoryMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long serialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    int insert(ConfigHistoryMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    int insertSelective(ConfigHistoryMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    List<ConfigHistoryMeta> selectByExample(ConfigHistoryMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    ConfigHistoryMeta selectByPrimaryKey(Long serialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ConfigHistoryMeta record, @Param("example") ConfigHistoryMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ConfigHistoryMeta record, @Param("example") ConfigHistoryMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfigHistoryMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfigHistoryMeta record);
}