package com.github.bh.aconf.persist.base.mapper;

import com.github.bh.aconf.persist.base.model.FilterMeta;
import com.github.bh.aconf.persist.base.model.FilterMetaExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FilterMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int countByExample(FilterMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int deleteByExample(FilterMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int insert(FilterMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int insertSelective(FilterMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    List<FilterMeta> selectByExample(FilterMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    FilterMeta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FilterMeta record, @Param("example") FilterMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FilterMeta record, @Param("example") FilterMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FilterMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FilterMeta record);
}