package com.github.bh.aconf.persist.base.model;

import java.util.Date;

public class BssMeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.developer
     *
     * @mbggenerated
     */
    private String developer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.tester
     *
     * @mbggenerated
     */
    private String tester;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.effective_type
     *
     * @mbggenerated
     */
    private Byte effectiveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.effective_time
     *
     * @mbggenerated
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.failure_time
     *
     * @mbggenerated
     */
    private Date failureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.app_id
     *
     * @mbggenerated
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.valid
     *
     * @mbggenerated
     */
    private Byte valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss.version
     *
     * @mbggenerated
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.id
     *
     * @return the value of bss.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.id
     *
     * @param id the value for bss.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.code
     *
     * @return the value of bss.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.code
     *
     * @param code the value for bss.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.name
     *
     * @return the value of bss.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.name
     *
     * @param name the value for bss.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.creator
     *
     * @return the value of bss.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.creator
     *
     * @param creator the value for bss.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.developer
     *
     * @return the value of bss.developer
     *
     * @mbggenerated
     */
    public String getDeveloper() {
        return developer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.developer
     *
     * @param developer the value for bss.developer
     *
     * @mbggenerated
     */
    public void setDeveloper(String developer) {
        this.developer = developer == null ? null : developer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.tester
     *
     * @return the value of bss.tester
     *
     * @mbggenerated
     */
    public String getTester() {
        return tester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.tester
     *
     * @param tester the value for bss.tester
     *
     * @mbggenerated
     */
    public void setTester(String tester) {
        this.tester = tester == null ? null : tester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.operator
     *
     * @return the value of bss.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.operator
     *
     * @param operator the value for bss.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.effective_type
     *
     * @return the value of bss.effective_type
     * @mbggenerated
     */
    public Byte getEffectiveType() {
        return effectiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.effective_type
     *
     * @param effectiveType the value for bss.effective_type
     * @mbggenerated
     */
    public void setEffectiveType(Byte effectiveType) {
        this.effectiveType = effectiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.effective_time
     *
     * @return the value of bss.effective_time
     *
     * @mbggenerated
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.effective_time
     *
     * @param effectiveTime the value for bss.effective_time
     *
     * @mbggenerated
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.failure_time
     *
     * @return the value of bss.failure_time
     *
     * @mbggenerated
     */
    public Date getFailureTime() {
        return failureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.failure_time
     *
     * @param failureTime the value for bss.failure_time
     *
     * @mbggenerated
     */
    public void setFailureTime(Date failureTime) {
        this.failureTime = failureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.create_time
     *
     * @return the value of bss.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.create_time
     *
     * @param createTime the value for bss.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.update_time
     *
     * @return the value of bss.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.update_time
     *
     * @param updateTime the value for bss.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.description
     *
     * @return the value of bss.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.description
     *
     * @param description the value for bss.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.app_id
     *
     * @return the value of bss.app_id
     *
     * @mbggenerated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.app_id
     *
     * @param appId the value for bss.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.valid
     *
     * @return the value of bss.valid
     *
     * @mbggenerated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.valid
     *
     * @param valid the value for bss.valid
     *
     * @mbggenerated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss.version
     *
     * @return the value of bss.version
     *
     * @mbggenerated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss.version
     *
     * @param version the value for bss.version
     *
     * @mbggenerated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BssMeta other = (BssMeta) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getDeveloper() == null ? other.getDeveloper() == null : this.getDeveloper().equals(other.getDeveloper()))
            && (this.getTester() == null ? other.getTester() == null : this.getTester().equals(other.getTester()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getEffectiveType() == null ? other.getEffectiveType() == null : this.getEffectiveType().equals(other.getEffectiveType()))
                && (this.getEffectiveTime() == null ? other.getEffectiveTime() == null : this.getEffectiveTime().equals(other.getEffectiveTime()))
            && (this.getFailureTime() == null ? other.getFailureTime() == null : this.getFailureTime().equals(other.getFailureTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getDeveloper() == null) ? 0 : getDeveloper().hashCode());
        result = prime * result + ((getTester() == null) ? 0 : getTester().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getEffectiveType() == null) ? 0 : getEffectiveType().hashCode());
        result = prime * result + ((getEffectiveTime() == null) ? 0 : getEffectiveTime().hashCode());
        result = prime * result + ((getFailureTime() == null) ? 0 : getFailureTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", creator=").append(creator);
        sb.append(", developer=").append(developer);
        sb.append(", tester=").append(tester);
        sb.append(", operator=").append(operator);
        sb.append(", effectiveType=").append(effectiveType);
        sb.append(", effectiveTime=").append(effectiveTime);
        sb.append(", failureTime=").append(failureTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", description=").append(description);
        sb.append(", appId=").append(appId);
        sb.append(", valid=").append(valid);
        sb.append(", version=").append(version);
        sb.append("]");
        return sb.toString();
    }
}