package com.github.bh.aconf.persist.base.model;

import java.util.Date;

public class FilterMeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.belong_id
     *
     * @mbggenerated
     */
    private Long belongId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.basis
     *
     * @mbggenerated
     */
    private String basis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.boundary
     *
     * @mbggenerated
     */
    private String boundary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.valid
     *
     * @mbggenerated
     */
    private Byte valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.belong_type
     *
     * @mbggenerated
     */
    private Byte belongType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.basis_type
     *
     * @mbggenerated
     */
    private Byte basisType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.id
     *
     * @return the value of filter.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.id
     *
     * @param id the value for filter.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.belong_id
     *
     * @return the value of filter.belong_id
     *
     * @mbggenerated
     */
    public Long getBelongId() {
        return belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.belong_id
     *
     * @param belongId the value for filter.belong_id
     *
     * @mbggenerated
     */
    public void setBelongId(Long belongId) {
        this.belongId = belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.basis
     *
     * @return the value of filter.basis
     *
     * @mbggenerated
     */
    public String getBasis() {
        return basis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.basis
     *
     * @param basis the value for filter.basis
     *
     * @mbggenerated
     */
    public void setBasis(String basis) {
        this.basis = basis == null ? null : basis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.operator
     *
     * @return the value of filter.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.operator
     *
     * @param operator the value for filter.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.boundary
     *
     * @return the value of filter.boundary
     *
     * @mbggenerated
     */
    public String getBoundary() {
        return boundary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.boundary
     *
     * @param boundary the value for filter.boundary
     *
     * @mbggenerated
     */
    public void setBoundary(String boundary) {
        this.boundary = boundary == null ? null : boundary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.creator
     *
     * @return the value of filter.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.creator
     *
     * @param creator the value for filter.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.create_time
     *
     * @return the value of filter.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.create_time
     *
     * @param createTime the value for filter.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.update_time
     *
     * @return the value of filter.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.update_time
     *
     * @param updateTime the value for filter.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.valid
     *
     * @return the value of filter.valid
     *
     * @mbggenerated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.valid
     *
     * @param valid the value for filter.valid
     *
     * @mbggenerated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.belong_type
     *
     * @return the value of filter.belong_type
     *
     * @mbggenerated
     */
    public Byte getBelongType() {
        return belongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.belong_type
     *
     * @param belongType the value for filter.belong_type
     *
     * @mbggenerated
     */
    public void setBelongType(Byte belongType) {
        this.belongType = belongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.basis_type
     *
     * @return the value of filter.basis_type
     *
     * @mbggenerated
     */
    public Byte getBasisType() {
        return basisType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.basis_type
     *
     * @param basisType the value for filter.basis_type
     *
     * @mbggenerated
     */
    public void setBasisType(Byte basisType) {
        this.basisType = basisType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FilterMeta other = (FilterMeta) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getBelongId() == null ? other.getBelongId() == null : this.getBelongId().equals(other.getBelongId()))
                && (this.getBasis() == null ? other.getBasis() == null : this.getBasis().equals(other.getBasis()))
                && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
                && (this.getBoundary() == null ? other.getBoundary() == null : this.getBoundary().equals(other.getBoundary()))
                && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
                && (this.getBelongType() == null ? other.getBelongType() == null : this.getBelongType().equals(other.getBelongType()))
                && (this.getBasisType() == null ? other.getBasisType() == null : this.getBasisType().equals(other.getBasisType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBelongId() == null) ? 0 : getBelongId().hashCode());
        result = prime * result + ((getBasis() == null) ? 0 : getBasis().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getBoundary() == null) ? 0 : getBoundary().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getBelongType() == null) ? 0 : getBelongType().hashCode());
        result = prime * result + ((getBasisType() == null) ? 0 : getBasisType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", belongId=").append(belongId);
        sb.append(", basis=").append(basis);
        sb.append(", operator=").append(operator);
        sb.append(", boundary=").append(boundary);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", valid=").append(valid);
        sb.append(", belongType=").append(belongType);
        sb.append(", basisType=").append(basisType);
        sb.append("]");
        return sb.toString();
    }
}