package com.github.bh.aconf.persist.base.model;

import java.util.Date;

public class PushMeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.bss_id
     *
     * @mbggenerated
     */
    private Long bssId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.effective_time
     *
     * @mbggenerated
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.sids
     *
     * @mbggenerated
     */
    private String sids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.sys
     *
     * @mbggenerated
     */
    private Byte sys;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.id
     *
     * @return the value of push.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.id
     *
     * @param id the value for push.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.bss_id
     *
     * @return the value of push.bss_id
     *
     * @mbggenerated
     */
    public Long getBssId() {
        return bssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.bss_id
     *
     * @param bssId the value for push.bss_id
     *
     * @mbggenerated
     */
    public void setBssId(Long bssId) {
        this.bssId = bssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.title
     *
     * @return the value of push.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.title
     *
     * @param title the value for push.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.description
     *
     * @return the value of push.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.description
     *
     * @param description the value for push.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.creator
     *
     * @return the value of push.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.creator
     *
     * @param creator the value for push.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.effective_time
     *
     * @return the value of push.effective_time
     *
     * @mbggenerated
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.effective_time
     *
     * @param effectiveTime the value for push.effective_time
     *
     * @mbggenerated
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.sids
     *
     * @return the value of push.sids
     *
     * @mbggenerated
     */
    public String getSids() {
        return sids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.sids
     *
     * @param sids the value for push.sids
     *
     * @mbggenerated
     */
    public void setSids(String sids) {
        this.sids = sids == null ? null : sids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.create_time
     *
     * @return the value of push.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.create_time
     *
     * @param createTime the value for push.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.update_time
     *
     * @return the value of push.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.update_time
     *
     * @param updateTime the value for push.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.state
     *
     * @return the value of push.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.state
     *
     * @param state the value for push.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.sys
     *
     * @return the value of push.sys
     *
     * @mbggenerated
     */
    public Byte getSys() {
        return sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.sys
     *
     * @param sys the value for push.sys
     *
     * @mbggenerated
     */
    public void setSys(Byte sys) {
        this.sys = sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PushMeta other = (PushMeta) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBssId() == null ? other.getBssId() == null : this.getBssId().equals(other.getBssId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getEffectiveTime() == null ? other.getEffectiveTime() == null : this.getEffectiveTime().equals(other.getEffectiveTime()))
            && (this.getSids() == null ? other.getSids() == null : this.getSids().equals(other.getSids()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getSys() == null ? other.getSys() == null : this.getSys().equals(other.getSys()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBssId() == null) ? 0 : getBssId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getEffectiveTime() == null) ? 0 : getEffectiveTime().hashCode());
        result = prime * result + ((getSids() == null) ? 0 : getSids().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getSys() == null) ? 0 : getSys().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bssId=").append(bssId);
        sb.append(", title=").append(title);
        sb.append(", description=").append(description);
        sb.append(", creator=").append(creator);
        sb.append(", effectiveTime=").append(effectiveTime);
        sb.append(", sids=").append(sids);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", state=").append(state);
        sb.append(", sys=").append(sys);
        sb.append("]");
        return sb.toString();
    }
}